version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  todo-list:
    build:
      context: ./
      dockerfile: ./apps/todo-list/Dockerfile
    container_name: todo-list
    env_file:
      - .env
    ports:
      - '3000:3001'
    depends_on:
      - rabbitmq
      - postgres
    command: npm run dev todo-list
    environment:
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq

  notifications:
    build:
      context: ./
      dockerfile: ./apps/notifications/Dockerfile
    container_name: notifications
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run dev notifications
    environment:
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq

volumes:
  postgresql_data:
  rabbitmq:

